Deadline banner
DFE-Digital/itt-mentoring-beta-prototype pull request #120
Opened 2024-07-03 15:22 UTC by TomBr0wn

Added banner component to alert the user to closing of claim window
app/views/claims/list.njk
and
app/views/support/organisations/claims/list.njk

https://github.com/DFE-Digital/itt-mentoring-beta-prototype/assets/78021112/6b6a1bcd-d41e-4af7-bd30-841f800d7c59

2024-07-03 15:54 UTC, simonwhatley requested changes

2024-07-03 15:54 UTC, simonwhatley commented on app/views/claims/list.njk
>      <div class="govuk-grid-column-full">
The banner should sit within a grid row and a full column.
```suggestion
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
      {% include "_includes/deadline-banner.njk" %}
    </div>
  </div>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
```

2024-07-03 15:54 UTC, simonwhatley commented on app/views/start.njk
>      <div class="govuk-grid-column-two-thirds">
```suggestion
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
      {% include "_includes/deadline-banner.njk" %}
    </div>
  </div>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
```

2024-07-03 15:54 UTC, simonwhatley commented on app/views/support/organisations/claims/list.njk
>      <div class="govuk-grid-column-two-thirds">
I'm not sure you need the claim banner in the support site as they typically won't be creating claims.

```suggestion
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
      {% include "_includes/deadline-banner.njk" %}
    </div>
  </div>

  <div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
```

2024-07-03 15:54 UTC, simonwhatley commented on app/views/_includes/deadline-banner.njk
> +{% endset %}
```suggestion
{% set deadlineBanner %}
  <p class="govuk-notification-banner__heading">
    Final closing date for claims: <strong>19 July 2024 by 11.59 pm</strong>
  </p>
{% endset %}
```

2024-07-04 09:11 UTC, simonwhatley requested changes

2024-07-04 09:11 UTC, simonwhatley commented on app/views/start.njk
> +    <div class="govuk-grid-column-full">
The page heading should only ever span two-thirds width

```suggestion
    <div class="govuk-grid-column-two-thirds">
```

2024-07-04 09:11 UTC, simonwhatley commented on app/views/support/organisations/claims/list.njk
> +    <div class="govuk-grid-column-full">
The page heading should only ever span two-thirds width

```suggestion
    <div class="govuk-grid-column-two-thirds">
```

2024-07-04 09:23 UTC, simonwhatley commented on app/views/support/organisations/claims/list.njk
> +      {# {% include "_includes/deadline-banner.njk" %} #}
If you're hiding the banner in support, it's probably a good idea to hide the whole grid row now that it is empty.

2024-07-04 13:51 UTC, simonwhatley approved these changes

2024-07-05 12:37 UTC, simonwhatley requested changes

2024-07-05 12:37 UTC, simonwhatley commented on app/views/start.njk
> +    <div class="govuk-grid-column-full-width">
The class name is `govuk-grid-column-full`:
```suggestion
    <div class="govuk-grid-column-full">
```

2024-07-08 09:25 UTC, TomBr0wn commented
@simonwhatley can you review again please

2024-07-08 13:18 UTC, merged

2024-08-27 19:38 UTC, simonwhatley commented
![](https://github.trello.services/images/mini-trello-icon.png) [Introduce a banner into the service to remind users of the deadline and encourage them to apply for funding](https://trello.com/c/b873PnPj/542-introduce-a-banner-into-the-service-to-remind-users-of-the-deadline-and-encourage-them-to-apply-for-funding)