Add service error pages
DFE-Digital/itt-mentoring-beta-prototype pull request #74
Opened 2024-04-16 14:18 UTC by simonwhatley

This PR adds error pages for:

- Page not found (404)
- Unexpected error (500)
- Service unavailable (503)
- User unauthorised

2024-04-16 14:34 UTC, petejobeskinandcarta requested changes
@LeaWelch has done copy for the unathorised page, it's on the ticket here.

https://trello.com/c/3hYeqkeQ/337-account-is-not-authorised-page

2024-04-16 14:40 UTC, LeaWelch submitted a review, later dismissed

2024-04-16 15:25 UTC, simonwhatley commented on app/views/errors/503.njk
> +      <p class="govuk-body">You’ll be able to use the service from 3pm on Tuesday, 16 April 2024.</p>
@LeaWelch, I've removed the contractions as requested.

2024-04-16 15:28 UTC, simonwhatley commented
@LeaWelch @petejobeskinandcarta this is ready for review

2024-04-16 15:41 UTC, olioldfield commented on app/views/errors/503.njk
> +      <p class="govuk-body">You’ll be able to use the service from 3pm on Tuesday, 16 April 2024.</p>
Does this mean the SLA needs to be updated to remove the contraction too?

You’ll get a response within 5 working days.

2024-04-16 15:58 UTC, simonwhatley commented on app/views/errors/503.njk
> +      <p class="govuk-body">You’ll be able to use the service from 3pm on Tuesday, 16 April 2024.</p>
My understanding is that negative contractions are a no-no. Others are okay.

2024-04-16 16:01 UTC, simonwhatley commented on app/views/errors/503.njk
> +      <p class="govuk-body">You’ll be able to use the service from 3pm on Tuesday, 16 April 2024.</p>
We should be consistent in the service, so we will need to change the footer content.

2024-04-16 19:13 UTC, simonwhatley commented
![](https://github.trello.services/images/mini-trello-icon.png) [Account is not authorised page](https://trello.com/c/3hYeqkeQ/337-account-is-not-authorised-page)

2024-04-18 14:50 UTC, olioldfield reviewed
All looks good, but one comment on the account unauthorised page:

If you work with us and think your account should be authorised, email [ittmentor.funding@education.gov.uk](mailto:ittmentor.funding@education.gov.uk).

I'm not sure if "if you work with us" is quite right - maybe:

If you think your account should be authorised, email
[ittmentor.funding@education.gov.uk](mailto:ittmentor.funding@education.gov.uk).

2024-04-18 20:37 UTC, merged